[tool.bumpversion]
current_version = "0.5.4"
commit = true
tag = true
pre_commit_hooks = ["uv lock", "git add uv.lock"]
search = "{current_version}"
replace = "{new_version}"
allow_dirty = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
