# Device Id - #ACOUFunction-DEVNumber-Location
device-id: ACOUBAT-DEV10-QEOP

# Device Location & Time
location:
  latitude: 51.5381
  longitude: -0.0099

timezone: Europe/London

# Audio Recording Parameters
start_recording: 12:00
end_recording: 08:00
